def is_valid_city(city):
    cities = [
        # United States
        "new york",
        "los angeles",
        "chicago",
        "houston",
        "phoenix",
        "philadelphia",
        "san antonio",
        "san diego",
        "dallas",
        "san jose",
        "austin",
        "jacksonville",
        "fort worth",
        "columbus",
        "charlotte",
        "san francisco",
        "indianapolis",
        "seattle",
        "denver",
        "washington",
        "boston",
        "miami",
        
        # United Kingdom
        "london",
        "manchester",
        "birmingham",
        "leeds",
        "liverpool",
        "newcastle",
        "sheffield",
        "bristol",
        "nottingham",
        "glasgow",
        "edinburgh",
        "cardiff",
        
        # Australia
        "sydney",
        "melbourne",
        "brisbane",
        "perth",
        "adelaide",
        "canberra",
        "hobart",
        "darwin",
        "gold coast",
        
        # Japan
        "tokyo",
        "osaka",
        "kyoto",
        "yokohama",
        "sapporo",
        
        # China
        "beijing",
        "shanghai",
        "hong kong",
        "guangzhou",
        "shenzhen",
        "chongqing",
        "chengdu",
        "wuhan",
        "tianjin",
        "nanjing",
        
        # Germany
        "berlin",
        "hamburg",
        "munich",
        "cologne",
        "frankfurt",
        "stuttgart",
        "dusseldorf",
        "bremen",
        "dresden",
        "leipzig",
        
        # France
        "paris",
        "marseille",
        "lyon",
        "toulouse",
        "nice",
        "nantes",
        "strasbourg",
        "montpellier",
        "bordeaux",
        "lille",
        
        # Canada
        "toronto",
        "montreal",
        "vancouver",
        "calgary",
        "edmonton",
        "ottawa",
        "quebec city",
        "winnipeg",
        "hamilton",
        "halifax",
        
        # Spain
        "madrid",
        "barcelona",
        "valencia",
        "seville",
        "zaragoza",
        "malaga",
        "murcia",
        "palma",
        "bilbao",
        "alicante",
        
        # Italy
        "rome",
        "milan",
        "naples",
        "turin",
        "palermo",
        "genoa",
        "bologna",
        "florence",
        "venice",
        "verona",
        
        # India
        "mumbai",
        "delhi",
        "bangalore",
        "hyderabad",
        "chennai",
        "kolkata",
        "ahmedabad",
        "pune",
        "surat",
        "jaipur",
        
        # Brazil
        "sao paulo",
        "rio de janeiro",
        "salvador",
        "brasilia",
        "fortaleza",
        "belo horizonte",
        "manaus",
        "curitiba",
        "recife",
        "porto alegre",
        
        # Russia
        "moscow",
        "saint petersburg",
        "novosibirsk",
        "ekaterinburg",
        "nizhny novgorod",
        "kazan",
        "chelyabinsk",
        "omsk",
        "samara",
        "rostov-on-don"
    ]
    
    return city.lower() in cities
